# Generated by Django 5.0.3 on 2024-05-22 16:35

import migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrate_sql.operations.CreateSQL(
            name="project_z_on_line",
            sql="\n        CREATE OR REPLACE FUNCTION project_z_on_line(line_2d geometry, line_z geometry, delta_z float)\n           RETURNS geometry\n           LANGUAGE plpgsql\n          AS\n        $$\n        declare\n           geom geometry;\n        begin\n            SELECT ST_MakeLine(points.geom) INTO geom from (\n                SELECT ST_SetSRID(\n                    ST_MakePoint(\n                        ST_X((points_2d.dp).geom),\n                        ST_Y((points_2d.dp).geom),\n                        ST_Z((points_z.dp).geom) + delta_z\n                    ),\n                    ST_Srid(line_2d)\n                ) as geom\n                FROM (\n                    SELECT ST_DumpPoints(line_z) AS dp) points_z\n                    INNER JOIN (SELECT ST_DumpPoints(line_2d) AS dp) points_2d\n                        ON (points_z.dp).path = (points_2d.dp).path\n                    ORDER BY (points_z.dp).path\n                ) points;\n           return geom;\n        end;\n        $$;\n        ",
            reverse_sql="\n            DROP FUNCTION project_z_on_line(line_2d geometry, line_z geometry);\n        ",
        ),
        migrate_sql.operations.CreateSQL(
            name="azimuth_along_line",
            sql="\n        CREATE OR REPLACE FUNCTION azimuth_along_line(geom geometry)\n           RETURNS integer[]\n           LANGUAGE plpgsql\n          AS\n        $$\n        declare\n           azimuts integer[];\n        begin\n            SELECT ARRAY(\n                SELECT\n                    CASE\n                     WHEN angle_post IS NULL THEN DEGREES(angle_ante)\n                     WHEN angle_ante IS NULL THEN DEGREES(angle_post)\n                     ELSE DEGREES(ATAN2(\n                       (SIN(angle_ante)+SIN(angle_post))/2,\n                       (COS(angle_ante)+COS(angle_post))/2\n                       ))\n                    END AS azm\n                    FROM (\n                        SELECT\n                            ST_Azimuth(LAG(dmp.geom) OVER (ORDER BY dmp.path), dmp.geom) AS angle_ante,\n                            ST_Azimuth(dmp.geom, LEAD(dmp.geom) OVER (ORDER BY dmp.path)) AS angle_post\n                            FROM ST_DumpPoints(geom) AS dmp\n                    ) azm_ante_post\n                ) INTO azimuts;\n           return azimuts;\n        end;\n        $$;\n        ",
            reverse_sql="\n            DROP FUNCTION azimuth_along_line(geom geometry);\n        ",
        ),
    ]
