# Generated by Django 5.0.3 on 2024-04-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="label",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
